name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  # build-and-test:
  unit-test: # Jobs runs in parallel
    runs-on: ubuntu-latest
    steps: # Steps run sequentially
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          # node-version: '20' # Specify the Node.js version
          cache: 'npm'

      # - name: Npm cache
      #   uses: actions/cache@v4
      #   id: npm-cache
      #   with:
      #     path: ~/.npm
      #     key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      # - name: Build
      #   run: npm run build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          # node-version: '20' # Specify the Node.js version
          cache: 'npm'
      #   uses: actions/setup-node@v4
      # - name: Npm cache
      #   uses: actions/cache@v4
      #   id: npm-cache
      #   with:
      #     path: ~/.npm
      #     key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      # - name: Run tests
      #   run: npm test
      - name: Build
        run: npm run build